//! Exercises the exact functions uniffi exports to Kotlin/Swift, called
//! directly as Rust (not through the FFI boundary - there is no Kotlin/Swift
//! toolchain in this repo's CI to drive that side). This proves the wrapper
//! bodies themselves are correct; `bindings/kotlin` and `bindings/swift`
//! (generated by `uniffi-bindgen`) prove the exported signatures are
//! well-formed for their respective languages.

use pqfile_mobile::{decrypt_bytes, decrypt_file, encrypt_bytes, encrypt_file, keygen, keygen_hybrid};

#[test]
fn bytes_roundtrip_all_levels() {
    for level in [512u16, 768, 1024] {
        let pair = keygen(level, None).unwrap();
        let plaintext = b"hello, post-quantum world".repeat(100);
        let ciphertext = encrypt_bytes(pair.public_key.clone(), plaintext.clone()).unwrap();
        assert_ne!(ciphertext, plaintext);
        let recovered = decrypt_bytes(pair.private_key, ciphertext, None).unwrap();
        assert_eq!(recovered, plaintext);
    }
}

#[test]
fn hybrid_roundtrip() {
    let pair = keygen_hybrid(None).unwrap();
    let plaintext = b"hybrid X25519 + ML-KEM-768".to_vec();
    let ciphertext = encrypt_bytes(pair.public_key, plaintext.clone()).unwrap();
    let recovered = decrypt_bytes(pair.private_key, ciphertext, None).unwrap();
    assert_eq!(recovered, plaintext);
}

#[test]
fn passphrase_protected_key() {
    let passphrase = "correct horse battery staple".to_string();
    let pair = keygen(768, Some(passphrase.clone())).unwrap();
    let ciphertext = encrypt_bytes(pair.public_key, b"secret".to_vec()).unwrap();

    let recovered = decrypt_bytes(pair.private_key.clone(), ciphertext.clone(), Some(passphrase)).unwrap();
    assert_eq!(recovered, b"secret");

    assert!(decrypt_bytes(pair.private_key.clone(), ciphertext.clone(), Some("wrong".to_string())).is_err());
    assert!(decrypt_bytes(pair.private_key, ciphertext, None).is_err());
}

#[test]
fn empty_plaintext_roundtrip() {
    let pair = keygen(768, None).unwrap();
    let ciphertext = encrypt_bytes(pair.public_key, Vec::new()).unwrap();
    let recovered = decrypt_bytes(pair.private_key, ciphertext, None).unwrap();
    assert!(recovered.is_empty());
}

#[test]
fn wrong_key_fails() {
    let a = keygen(768, None).unwrap();
    let b = keygen(768, None).unwrap();
    let ciphertext = encrypt_bytes(a.public_key, b"for A, not B".to_vec()).unwrap();
    assert!(decrypt_bytes(b.private_key, ciphertext, None).is_err());
}

#[test]
fn file_roundtrip() {
    let pair = keygen(768, None).unwrap();
    let plaintext = b"streamed to disk".repeat(10_000);

    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("input.bin");
    let encrypted = dir.path().join("input.bin.pqf");
    let decrypted = dir.path().join("output.bin");
    std::fs::write(&src, &plaintext).unwrap();

    encrypt_file(
        pair.public_key,
        src.to_str().unwrap().to_string(),
        encrypted.to_str().unwrap().to_string(),
    )
    .unwrap();
    assert_ne!(std::fs::read(&encrypted).unwrap(), plaintext);

    decrypt_file(
        pair.private_key,
        encrypted.to_str().unwrap().to_string(),
        decrypted.to_str().unwrap().to_string(),
        None,
    )
    .unwrap();
    assert_eq!(std::fs::read(&decrypted).unwrap(), plaintext);
}

#[test]
fn invalid_pem_fails() {
    assert!(encrypt_bytes("not a pem".to_string(), b"data".to_vec()).is_err());
}
