from typing import Optional, Tuple

class PqfileError(Exception): ...

def keygen(level: int = 768, passphrase: Optional[str] = None) -> Tuple[str, str]: ...
def keygen_hybrid(passphrase: Optional[str] = None) -> Tuple[str, str]: ...
def encrypt_bytes(pubkey_pem: str, plaintext: bytes) -> bytes: ...
def decrypt_bytes(
    privkey_pem: str, ciphertext: bytes, passphrase: Optional[str] = None
) -> bytes: ...
def encrypt_file(pubkey_pem: str, input_path: str, output_path: str) -> None: ...
def decrypt_file(
    privkey_pem: str,
    input_path: str,
    output_path: str,
    passphrase: Optional[str] = None,
) -> None: ...
