
# cargo-vet audits file

[audits]

[[trusted.pqfile]]
criteria = "safe-to-deploy"
user-id = 419333 # Derek (dangel34)
start = "2026-05-28"
end = "2027-06-29"

[[trusted.pqfile-cli]]
criteria = "safe-to-deploy"
user-id = 419333 # Derek (dangel34)
start = "2026-05-28"
end = "2027-06-29"
