[package]
name = "pqfile-gui"
version = "0.1.0"
edition = "2021"
autobins = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pqfile = { path = "../pqfile" }
eframe = { version = "0.29", features = ["default_fonts"] }
rfd = "0.14"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ureq = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "HtmlCanvasElement",
    "HtmlAnchorElement",
    "HtmlElement",
    "Element",
    "Node",
    "Url",
    "Blob",
] }
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }
