/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Decrypts a `.pqf`-format buffer produced by [`encrypt_bytes`] (or the
 * pqfile CLI/GUI) using the matching private key.
 */
export declare function decryptBytes(privkeyPem: string, ciphertext: Buffer, passphrase?: string | undefined | null): Promise<Buffer>

/**
 * Decrypts the `.pqf` file at `input_path` to `output_path`, streaming so
 * memory use stays flat regardless of file size.
 */
export declare function decryptFile(privkeyPem: string, inputPath: string, outputPath: string, passphrase?: string | undefined | null): Promise<void>

/**
 * Encrypts `plaintext` to a `.pqf`-format buffer for the recipient identified
 * by `pubkey_pem`.
 */
export declare function encryptBytes(pubkeyPem: string, plaintext: Buffer): Promise<Buffer>

/**
 * Encrypts the file at `input_path` to `output_path`, streaming so memory
 * use stays flat regardless of file size.
 */
export declare function encryptFile(pubkeyPem: string, inputPath: string, outputPath: string): Promise<void>

/**
 * Generates an ML-KEM key pair. `level` must be 512, 768, or 1024 (default 768).
 * If `passphrase` is given, the private key PEM is Argon2id + AES-256-GCM encrypted.
 */
export declare function keygen(level?: number | undefined | null, passphrase?: string | undefined | null): Promise<KeyPair>

/** Generates a hybrid X25519 + ML-KEM-768 key pair. */
export declare function keygenHybrid(passphrase?: string | undefined | null): Promise<KeyPair>

/** A generated ML-KEM (or hybrid X25519+ML-KEM) key pair, PEM-encoded. */
export interface KeyPair {
  publicKey: string
  privateKey: string
}
